dist: trusty
sudo: false

language: bash

branches:
  only:
    - master

notifications:
  email: false

addons:
  apt:
    packages:
      - curl

before_script:
- mkdir chnroute

script:
- pushd chnroute
- curl 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | grep ipv4 | grep CN | awk -F\| '{ printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > chnroute.txt
- popd

after_success:
- pushd chnroute
- ls -al
- popd
