dist: trusty
sudo: false

notifications:
  email: false

branches:
  only:
    - master

language: bash

env:
  secure: "U4S7PKECmegpzEoHwblNnRQ4Wgzn7fE4nYv+GGbumxd98z71RcoKBJP0hQg9zxHRFQdPmUid9sRPW7P6E2HPwPVCeWjTkntWMFcF2PZr9fW/beO31LUe5R+0KS7BaKl2IVrHJeSURpOtv3RMJRzo838WfzuiSlD5EumJ23+2e0GDjcoREWw+p3f7cDi8De4PUoVN1atig2ZN/Y6Gr8JNSbAAjUj2ECd/BQRRrIxe/ri/7dHs5Uot9gPbG2VNCAi+srla9fSLUrtXYRY5k3uI9FyCb2yu8MIW0IeiJrx06onYd6F3pJ49QxJfsRJtFEa3FMmMBE2U4XlnTq/pMdcVgCqle4KSK2G0WQ4oU7l3Fbk9qqTVHOZIJQBPkSQUbBeQ1MBSiWR0O6t0AVbNDsWaO/PFb2Y8qQWiJC9XVCZ+t6xE/InUyX/kom1NuEd86GhESpr6lxGImJ4WIlUYZ37eWI9vZBqwKp1yVzMEmIUkld4/no6/IWtWcdxYVsI62aZNUtHuHFelGaR3tC2M3w+SoEfcciXM++4gcUHyBqZTRmkAsCbdxB4ag7IZG83Ij0GcfSyDc3UVU//A6Q4e7E1py1GsTssVTrbcfV3Xwzd9rroyXlMo1c6ACMV1nT5MInBrxxykySJ/qkPKPfTtcFUik5HLcp/xhhJlfaQOha7ZFgA="

addons:
  apt:
    packages:
      - curl

before_script:
  - export TZ=Asia/Shanghai
  - git config --global user.name "travis-ci"
  - git config --global user.email "travis-ci@github.com"
  - git config --global log.date iso

script:
  # chnroute
  - mkdir -p dist/chnroute
  - pushd dist/chnroute
  - curl 'http://ftp.apnic.net/apnic/stats/apnic/delegated-apnic-latest' | grep ipv4 | grep CN | awk -F\| '{ printf("%s/%d\n", $4, 32-log($5)/log(2)) }' > chnroute.txt
  - popd
  
  # dnsmasq rules
  - mkdir -p dist/dnsmasq
  - pushd dist/dnsmasq
  - echo -e "#\n# easylistchina+easylist - `date +'%Y-%m-%d %T'`\n#" >> adblock.conf
  - curl https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt | grep ^\|\|[^\*]*\^$ | sed -e 's:||:address\=\/:' -e 's:\^:/127\.0\.0\.1:' >> adblock.conf
  - echo -e "\n\n" >> adblock.conf
  - echo -e "#\n# ABP-FX - `date +'%Y-%m-%d %T'`\n#" >> adblock.conf
  - curl https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/ABP-FX.txt | grep ^\|\|[^\*]*\^$ | sed -e 's:||:address\=\/:' -e 's:\^:/127\.0\.0\.1:' >> adblock.conf
  - echo -e "\n\n" >> adblock.conf
  - echo -e "#\n# custom rules - `date +'%Y-%m-%d %T'`\n#" >> adblock.conf
  - curl https://pexcn.github.io/dnsmasq-rules/rules.conf >> adblock.conf
  - popd

after_success:
  - git clone https://github.com/pexcn/daily.git -b gh-pages upload --depth 5
  - pushd upload
  - rm -r *
  - cp -r ../dist/* .
  - git add --all
  - git commit -m "`date +'%Y-%m-%d %T'`"
  - git push --quiet "https://${token}@github.com/pexcn/daily.git" HEAD:gh-pages
  - popd
